# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        NeverLoot
    description:  Application de gestion de raid de la guilde Never Mind
    #keywords:     symfony, project
    language:     fr
    #robots:       index, follow

  stylesheets:
    - jquery-ui-1.8.17.custom.css
    - jquery.fancybox-1.3.4.css
    - main.css

  javascripts:
    - jquery-1.7.js
    - jquery.cookie.js
    - jquery-ui-1.8.17.custom.min.js
    - menu_deroulant/ddsmoothmenu.js
    - fancybox/jquery.fancybox-1.3.4.pack.js
    - home.js
    - perso.js
    - raid.js
    - http://static.wowhead.com/widgets/power.js

  has_layout:     true
  layout:         layout
