<?php

/**
 * Skeleton subclass for representing a row from the 'wow_boss' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * 12/23/11 16:58:36
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Boss extends BaseBoss
{
    /** liste des persos pour lequels init les objets */
    protected $currentListPerso = array();

    /** liste des objets du boss */
    protected $listeObjets = false;

    /** query custom pour les objets */
    protected $objectQuery;

    /**
     * renvoie la liste des objets du boss
     * @param  bool  $heroique flag à activer pour renvoyer les objets en hm
     * @return array
     */
    public function getListeObjets($heroique = false)
    {
        $this->listeObjets = $this->getObjectQuery()
            ->filterByHeroique($heroique ? 1 : 0)
            ->orderByIdSlot1()
            ->find();

        foreach($this->listeObjets as $objet)
            $objet->initPersosPrioritaires($this->currentListPerso);

        return $this->listeObjets;
    }

    /**
     * défini la liste des objets du boss
     * @param array $liste liste d'objets
     */
    public function setListeObjets($liste)
    {
        $this->listeObjets = $liste;

        return $this;
    }

    /**
     * défini la liste des persos
     * @param  array $listePersos
     * @return Boss
     */
    public function setListePersos($listePersos)
    {
        $this->currentListPerso = $listePersos;

        return $this;
    }

    /**
     * définie une requete custom pour récup les objets
     * @param  ObjetQuery $objectQuery
     * @return Boss
     */
    public function setObjectQuery(ObjetQuery $objectQuery)
    {
        $this->objectQuery = $objectQuery;

        return $this;
    }

    /**
     * renvoie une requete pour récup les objets du boss
     * @return ObjetQuery
     */
    public function getObjectQuery()
    {
        if(!empty($this->objectQuery))

            return $this->objectQuery;

        return ObjetQuery::create()
            ->useSourceObjetQuery()
                ->filterByIdType($this->getIdBoss())
                ->filterByType('Boss')
            ->endUse();
    }

} // Boss
