<?php

/**
 * Skeleton subclass for performing query and update operations on the 'wow_buff_type' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Feb  4 15:40:02 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BuffTypePeer extends BaseBuffTypePeer
{
}
