<?php

/**
 * Skeleton subclass for performing query and update operations on the 'wow_perso' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * 12/23/11 16:58:37
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class PersoQuery extends BasePersoQuery
{
    /**
     * ajoute un filtre sur le perso main
     * @return PersoQuery
     */
    public function filterMain()
    {
        return $this->filterByIsMain(1);
    }

    /**
     * ajoute un filtre sur les rerolls
     * @return PersoQuery
     */
    public function filterReroll()
    {
        return $this->filterByIsMain(0);
    }

    /**
     * ordonne la requete par ordre de role (tank>heal>dps)
     * @param  string     $dir direction de tri
     * @return PersoQuery
     */
    public function ordreByRole($dir = 'asc')
    {
        return $this->join('Perso.SpeRelatedByIdSpe1')
            ->orderBy('SpeRelatedByIdSpe1.IdRole', $dir)
            ->orderBy('Perso.IdClasse')
            ->orderBy('Perso.Nom');
    }

} // PersoQuery
