<?php

/**
 * Skeleton subclass for representing a row from the 'wow_perso_soiree' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * Wed Feb  1 14:56:23 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class PersoSoiree extends BasePersoSoiree
{
} // PersoSoiree
