<?php

/**
 * Skeleton subclass for representing a row from the 'wow_raid' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * 12/23/11 16:58:37
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Raid extends BaseRaid
{
    /**
     * renvoie la liste des boss du raid
     * @return array
     */
    public function getListeBoss()
    {
        $listeBoss = BossQuery::create()
            ->filterByIdRaid($this->getIdRaid())
            ->orderByOrdre('asc')
            ->find();

        // création d'un boss virtuel pour les loots de zone
        $raidAsBoss = new Boss();
        $raidAsBoss->setNomFr($this->getNomFr());
        $raidAsBoss->setIdBoss($this->getIdRaid());
        $raidAsBoss->setImage($this->getImage());
        $raidAsBoss->setObjectQuery(
            ObjetQuery::create()
                ->where('Objet.JsonSource not like ?', '%skill%')
                ->useSourceObjetQuery()
                    ->filterByType('Raid')
                    ->filterByIdType($this->getIdRaid())
                ->endUse()
        );

        $listeBoss->prepend($raidAsBoss);

        return $listeBoss;
    }

} // Raid
