<?php

/**
 * Skeleton subclass for performing query and update operations on the 'wow_soiree' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * 12/23/11 16:58:38
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SoireeQuery extends BaseSoireeQuery
{
    /**
     * ajoute un filtre sur le mois en paramètre
     * @param string $yearMonth année/mois pour lequel récup les dates
     */
    public function filterByMonth($yearMonth)
    {
        $firstDay = strtotime($yearMonth);
        $nbDayInMonth = intval(date('t', $firstDay));

        return $this->filterByDate(array(
            'min'=> $firstDay,
            'max' => $firstDay + 3600*24*$nbDayInMonth
        ));
    }

    /**
     * ajoute le filtre des raids à venir
     * @return SoireeQuery
     */
    public function filterNext()
    {
        return $this->filterByDate(array('min' => strtotime(date('Y-m-d 00:00:00'))));
    }

    /**
     * ajoute le filtre des raids passés
     * @return SoireeQuery
     */
    public function filterPrev()
    {
        return $this->filterByDate(array('max' => strtotime(date('Y-m-d 23:59:59', time()-24*3600))));
    }

} // SoireeQuery
