<?php

/**
 * Skeleton subclass for performing query and update operations on the 'wow_wishlist_objet' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * 12/23/11 18:12:12
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WishlistObjetQuery extends BaseWishlistObjetQuery
{
} // WishlistObjetQuery
